name: example
version: 1.0.0
description: Charts-Flutter Demo
publish_to: 'none'
environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.1
  intl: ">=0.17.0 < 0.18.0"
flutter:
  uses-material-design: true
