name: example
version: 1.0.0
description: Charts-Flutter Demo
publish_to: 'none'
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  charts_flutter:
    path: ../
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.12.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
