name: charts_common
version: 0.12.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  intl: ^0.20.2
  logging: ^1.2.0
  meta: ^1.12.0
  vector_math: ^2.1.4

dev_dependencies:
  mockito: ^5.4.2
  mocktail: ^1.0.1
  test: ^1.25.5
